import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { cookies } from "next/headers";
import { defaultTheme } from "config";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const chillax = localFont({
	src: "./fonts/chillax.woff2",
	display: "swap",
	variable: "--font-chillax",
});

const calsans = localFont({
	src: "./fonts/calsans-semi.woff2",
	variable: "--font-calsans",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const theme = cookies().get("ck_theme")?.value || defaultTheme;
	return (
		<ClerkProvider>
			<html
				lang="en"
				className={`${chillax.variable} ${calsans.variable} ${inter.variable}`}
			>
				<body className={`${theme === "dark" ? "dark" : ""}`}>
					<NuqsAdapter>{children}</NuqsAdapter>
				</body>
			</html>
		</ClerkProvider>
	);
}

export const runtime = "edge";
